settings list:
    s0:
        [
            ['lib', 'tow', 'jk', 'scw','lc', 'stem'],
            ['pac', 'tow', 'jk']
        ]
    s1:
        [
            ['lib', 'tow', 'jk', 'scw','lc', 'stem'],
            ['pac',  'tow', 'jk'],
            ['com', 'tow', 'jk', 'scw', 'lc', 'sw']
        ]
    s2: 
        [
            ['lib', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['pac', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['pm', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['pv', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['com', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['c', 'tow', 'jk', 'scw','lc', 'sw', 'stem']
        ]

    s3: 
        [
            ['pac', 'tow', 'jk'],
            ['lib', 'tow', 'scw', 'jk', 'lc', 'stem'],
            ['pm', 'tow', 'scw', 'jk', 'lc', 'sw']
        ]
    s4: 
        [ 
            ['lib', 'tow', 'scw', 'jk', 'lc', 'stem'],
            ['pac', 'tow', 'jk',],
            ['c', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['pm', 'tow', 'scw', 'jk', 'lc', 'sw', 'stem'],
            ['pv', 'tow', 'jk', 'scw','lc', 'sw', 'stem']
        ]
    s5: 
        [
            ['lib', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['pac', 'tow', 'jk'],
            ['pm', 'tow', 'jk', 'scw','lc', 'sw'],
            ['pv', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['com', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['c', 'tow', 'jk', 'scw','lc', 'sw', 'stem']
        ]
    s6: 
        [
            ['lib', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['pac', 'tow', 'jk'],
            ['pm', 'tow', 'jk', 'scw','lc', 'sw'],
            ['pv', 'tow', 'jk', 'scw','lc', 'sw'],
            ['com', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['c', 'tow', 'jk', 'scw','lc', 'sw']
        ]
    s7: 
        [
            ['lib', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['pac', 'tow', 'jk'],
            ['pm', 'tow', 'jk', 'scw','lc' ],
            ['pv', 'tow', 'jk', 'scw','lc' ],
            ['com', 'tow', 'jk', 'scw','lc', 'sw', 'stem'],
            ['c', 'tow', 'jk', 'scw','lc']
        ]
