file locations:
    jabref:
        system folder: 'architectures/JabRef_architecture'
        raw data: 'Data/jabref/rawdata.csv'
        tmp data: 'Data/jabref/tmp.csv'
        single setting preprocessing: 'Data/jabref/single_prep.csv'
        preprocess comparisons: 'Data/jabref/prep_comparisons.csv'
        data size percentage: 'Data/jabref/size_percentage.csv'
        data size abs num: 'Data/jabref/size_abs.csv'
    prom:
        system folder: 'architectures/ProM_architecture'
        raw data: 'Data/prom/rawdata.csv'
        tmp data: 'Data/prom/tmp.csv'
        single setting preprocessing: 'Data/prom/single_prep.csv'
        preprocess comparisons: 'Data/prom/prep_comparisons.csv'
        data size percentage: 'Data/prom/size_percentage.csv'
        data size abs num: 'Data/prom/size_abs.csv'
    team:
        system folder: 'architectures/TEAMMATES_architecture'
        raw data: 'Data/team/rawdata.csv'
        tmp data: 'Data/team/tmp.csv'
        single setting preprocessing: 'Data/team/single_prep.csv'
        preprocess comparisons: 'Data/team/prep_comparisons.csv'
        data size percentage: 'Data/team/size_percentage.csv'
        data size abs num: 'Data/team/size_abs.csv'
preprocess settings list:
    s0:
        [
            ['lib', 'tow', 'scw', 'jk', 'lc', 'stem'],
            ['pac', 'tow', 'jk'],
        ]
    s1: 
        [ 
            ['lib', 'tow', 'scw', 'jk', 'lc', 'stem'],
            ['pac', 'tow', 'jk',],
            ['c', 'tow', 'jk', 'scw', 'lc'],
        ]
    s2:
        [
            ['lib', 'tow', 'scw', 'jk', 'lc', 'stem'],
            ['pac', 'tow', 'jk'],
            ['com', 'tow', 'lc', 'sw', 'stem'],
        ]
    s3: 
        [
            ['lib', 'tow', 'scw', 'jk', 'lc', 'stem'],
            ['pac', 'tow', 'jk'],
            ['pm', 'tow', 'jk', 'scw', 'lc', 'sw'],
        ]

    s4: 
        [
            ['lib', 'tow', 'scw', 'jk', 'lc', 'stem'],
            ['pac', 'tow', 'jk'],
            ['pv', 'tow', 'jk', 'scw', 'lc'],
        ]
    s5: 
        [
            ['lib', 'tow', 'scw', 'jk', 'lc', 'stem'],
            ['pac', 'tow', 'jk'],
            ['pm', 'tow', 'jk', 'scw', 'lc', 'sw'],
            ['pv', 'tow', 'jk', 'scw', 'lc'],
        ]
    s6: 
        [
            ['lib', 'tow', 'scw', 'jk', 'lc', 'stem'],
            ['pac', 'tow', 'jk'],
            ['c', 'tow', 'jk', 'scw', 'lc'],
            ['pm', 'tow', 'jk', 'scw', 'lc', 'sw'],
            ['pv', 'tow', 'jk', 'scw', 'lc'],
        ]
    s7: 
        [
            ['lib', 'tow', 'scw', 'jk', 'lc', 'stem'],
            ['pac', 'tow', 'jk'],
            ['c', 'tow', 'jk', 'scw', 'lc'],
            ['com', 'tow', 'lc', 'sw', 'stem'],
            ['pm', 'tow', 'jk', 'scw', 'lc', 'sw'],
            ['pv', 'tow', 'jk', 'scw', 'lc'],
        ]
